kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta2
metadata:
  name: hpa-fiap-grupo-20
  namespace: entrega-grupo-20
  selfLink: >-
    /apis/autoscaling/v2beta2/namespaces/entrega-grupo-20/horizontalpodautoscalers/hpa-fiap-grupo-20
  uid: 4c501143-9d5b-40ff-863d-14798391500f
  resourceVersion: '47075177'
  creationTimestamp: '2022-03-31T19:28:46Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: autoscaling/v2beta2
      time: '2022-03-31T19:28:46Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          'f:maxReplicas': {}
          'f:metrics': {}
          'f:minReplicas': {}
          'f:scaleTargetRef':
            'f:apiVersion': {}
            'f:kind': {}
            'f:name': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: autoscaling/v1
      time: '2022-03-31T19:29:01Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:autoscaling.alpha.kubernetes.io/conditions': {}
            'f:autoscaling.alpha.kubernetes.io/current-metrics': {}
        'f:status':
          'f:currentCPUUtilizationPercentage': {}
          'f:currentReplicas': {}
          'f:desiredReplicas': {}
spec:
  scaleTargetRef:
    kind: Deployment
    name: fiap-grupo-20
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
status:
  currentReplicas: 2
  desiredReplicas: 2
  currentMetrics:
    - type: Resource
      resource:
        name: cpu
        current:
          averageValue: 1m
          averageUtilization: 30
  conditions:
    - type: AbleToScale
      status: 'True'
      lastTransitionTime: '2022-03-31T19:29:01Z'
      reason: ReadyForNewScale
      message: recommended size matches current size
    - type: ScalingActive
      status: 'True'
      lastTransitionTime: '2022-03-31T19:29:01Z'
      reason: ValidMetricFound
      message: >-
        the HPA was able to successfully calculate a replica count from cpu
        resource utilization (percentage of request)
    - type: ScalingLimited
      status: 'False'
      lastTransitionTime: '2022-03-31T19:29:01Z'
      reason: DesiredWithinRange
      message: the desired count is within the acceptable range
