kind: Secret
apiVersion: v1
metadata:
  name: sercrets-app
  namespace: entrega-grupo-20
  selfLink: /api/v1/namespaces/entrega-grupo-20/secrets/sercrets-app
  uid: 128c3b61-da34-4a43-a5b7-d03978d906b2
  resourceVersion: '47138490'
  creationTimestamp: '2022-03-31T20:33:13Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: v1
      time: '2022-03-31T20:33:13Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:password': {}
        'f:type': {}
data:
  password: IUhqSktNWG9uUG56
type: Opaque
